# src/config/__init__.py
"""
配置模块入口
从 settings 导入所有配置变量，保持向后兼容
"""

from src.config.settings import settings

# 导出所有在 run.py 及其他模块中使用的变量
# 路径
ROOT_DIR = settings.ROOT_DIR
DATA_DIR = settings.DATA_DIR
OUTPUT_DIR = settings.OUTPUT_DIR

# 性能
MAX_WORKERS = settings.MAX_WORKERS
TIMEOUT = settings.TIMEOUT
HTTP_TIMEOUT = settings.HTTP_TIMEOUT

# ffmpeg
FFMPEG_ENABLE = settings.FFMPEG_ENABLE
FFMPEG_MODE = settings.FFMPEG_MODE
FFPROBE_CACHE_HOURS = settings.FFPROBE_CACHE_HOURS
FFMPEG_WORKERS = settings.FFMPEG_WORKERS

# 缓存
CACHE_HOURS = settings.CACHE_HOURS
CACHE_RAW_HOURS = settings.CACHE_RAW_HOURS
CACHE_SPEED_HOURS = settings.CACHE_SPEED_HOURS

# 功能开关
ENABLE_DEMO_FILTER = settings.ENABLE_DEMO_FILTER
ENABLE_ALIAS = settings.ENABLE_ALIAS
ENABLE_BLACKLIST = settings.ENABLE_BLACKLIST
DATABASE_ENABLE = settings.DATABASE_ENABLE
ENABLE_INCREMENTAL_FETCH = settings.ENABLE_INCREMENTAL_FETCH
ENABLE_JSON_OUTPUT = settings.ENABLE_JSON_OUTPUT
ENABLE_LITE_VERSION = settings.ENABLE_LITE_VERSION
ENABLE_EPG_OUTPUT = settings.ENABLE_EPG_OUTPUT
DEMO_MATCH_MODE = settings.DEMO_MATCH_MODE

# 合并
MAX_SOURCES_PER_CHANNEL = settings.MAX_SOURCES_PER_CHANNEL

# 测速与黑名单
MAX_RETRY_BEFORE_BLACKLIST = settings.MAX_RETRY_BEFORE_BLACKLIST
SLOW_SPEED_THRESHOLD = settings.SLOW_SPEED_THRESHOLD
DOWNLOAD_CHUNK_SIZE = settings.DOWNLOAD_CHUNK_SIZE

# 自治模式
AUTONOMOUS_MODE = settings.AUTONOMOUS_MODE
AUTO_UPDATE_STABLE = settings.AUTO_UPDATE_STABLE
AUTO_REPLACE_FAILED = settings.AUTO_REPLACE_FAILED
QUALITY_CHECK_INTERVAL = settings.QUALITY_CHECK_INTERVAL
CANDIDATE_OBSERVATION_HOURS = settings.CANDIDATE_OBSERVATION_HOURS
CANDIDATE_MIN_SUCCESS = settings.CANDIDATE_MIN_SUCCESS
CANDIDATE_MIN_SUCCESS_RATE = settings.CANDIDATE_MIN_SUCCESS_RATE
CANDIDATE_MAX_LATENCY = settings.CANDIDATE_MAX_LATENCY
AUTO_PROMOTE_THRESHOLD = settings.AUTO_PROMOTE_THRESHOLD

# 健康预测
HEALTH_HISTORY_DAYS = settings.HEALTH_HISTORY_DAYS
PREDICT_THRESHOLD = settings.PREDICT_THRESHOLD

# 固定源优化
ENABLE_FIXED_OPTIMIZATION = settings.ENABLE_FIXED_OPTIMIZATION
FIXED_OPTIMIZATION_THRESHOLD = settings.FIXED_OPTIMIZATION_THRESHOLD

# IPTV 源列表（关键！）
IPTV_SOURCES = settings.IPTV_SOURCES
RAW_SOURCES = settings.RAW_SOURCES
DIRECT_SOURCES = settings.DIRECT_SOURCES

# 代理
ENABLE_GITHUB_PROXY = settings.ENABLE_GITHUB_PROXY
GITHUB_RAW_PROXIES = settings.GITHUB_RAW_PROXIES
GITHUB_PROXY_TIMEOUT = settings.GITHUB_PROXY_TIMEOUT

# 其他
HEADERS = settings.HEADERS

# 兼容旧代码的变量（在 config.py 中原有的）
PROXY = ""  # 不再使用
ENABLE_RETRY = True
RETRY_MAX_ATTEMPTS = 3
RETRY_BACKOFF_FACTOR = 2
RETRY_MAX_WAIT = 60

# 文件路径
DEMO_FILE = ROOT_DIR / "demo.txt"
ALIAS_FILE = ROOT_DIR / "alias.txt"
BLACKLIST_FILE = ROOT_DIR / "blacklist.txt"
DATABASE_PATH = DATA_DIR / "iptv_cache.db"

# 输出分类顺序
OUTPUT_CATEGORY_ORDER = ["央视", "卫视", "地方", "港澳台"]
CCTV_ORDER = [
    "CCTV-1", "CCTV-2", "CCTV-3", "CCTV-4", "CCTV-5", "CCTV-5+", "CCTV-6",
    "CCTV-7", "CCTV-8", "CCTV-9", "CCTV-10", "CCTV-11", "CCTV-12", "CCTV-13",
    "CCTV-14", "CCTV-15", "CCTV-16", "CCTV-17", "CCTV-4K", "CCTV-8K",
    "CCTV世界地理", "CCTV央视台球", "CCTV女性时尚", "CCTV怀旧剧场",
    "CCTV第一剧场", "CCTV风云足球", "CCTV老故事", "CGTN", "CGTN俄语",
    "CGTN法语", "CGTN纪录", "CGTN西语", "CGTN阿语"
]

M3U_FILE = "tv.m3u"
TXT_FILE = "tv.txt"

# 省份列表（从 constants 导入，避免循环）
from src.constants import PROVINCES, HK_MACAU_TAIWAN_KEYWORDS
PROVINCES = PROVINCES
HK_MACAU_TAIWAN_KEYWORDS = HK_MACAU_TAIWAN_KEYWORDS
