# src/config.py
"""
配置文件 - 向后兼容层
所有配置项从 settings 模块导入，保持原有变量名不变
"""

from src.settings import settings

ROOT_DIR = settings.ROOT_DIR
DATA_DIR = settings.DATA_DIR
OUTPUT_DIR = settings.OUTPUT_DIR

MAX_WORKERS = settings.MAX_WORKERS
TIMEOUT = settings.TIMEOUT
HTTP_TIMEOUT = settings.HTTP_TIMEOUT

FFMPEG_ENABLE = settings.FFMPEG_ENABLE
FFMPEG_MODE = settings.FFMPEG_MODE
FFPROBE_CACHE_HOURS = settings.FFPROBE_CACHE_HOURS
FFMPEG_WORKERS = settings.FFMPEG_WORKERS

CACHE_HOURS = settings.CACHE_HOURS
CACHE_RAW_HOURS = settings.CACHE_RAW_HOURS
CACHE_SPEED_HOURS = settings.CACHE_SPEED_HOURS

ENABLE_DEMO_FILTER = settings.ENABLE_DEMO_FILTER
ENABLE_ALIAS = settings.ENABLE_ALIAS
ENABLE_BLACKLIST = settings.ENABLE_BLACKLIST
DATABASE_ENABLE = settings.DATABASE_ENABLE
ENABLE_INCREMENTAL_FETCH = settings.ENABLE_INCREMENTAL_FETCH
ENABLE_JSON_OUTPUT = settings.ENABLE_JSON_OUTPUT
ENABLE_LITE_VERSION = settings.ENABLE_LITE_VERSION
ENABLE_EPG_OUTPUT = settings.ENABLE_EPG_OUTPUT
DEMO_MATCH_MODE = settings.DEMO_MATCH_MODE

MAX_SOURCES_PER_CHANNEL = settings.MAX_SOURCES_PER_CHANNEL

MAX_RETRY_BEFORE_BLACKLIST = settings.MAX_RETRY_BEFORE_BLACKLIST
SLOW_SPEED_THRESHOLD = settings.SLOW_SPEED_THRESHOLD
DOWNLOAD_CHUNK_SIZE = settings.DOWNLOAD_CHUNK_SIZE

AUTONOMOUS_MODE = settings.AUTONOMOUS_MODE
AUTO_UPDATE_STABLE = settings.AUTO_UPDATE_STABLE
AUTO_REPLACE_FAILED = settings.AUTO_REPLACE_FAILED
QUALITY_CHECK_INTERVAL = settings.QUALITY_CHECK_INTERVAL
CANDIDATE_OBSERVATION_HOURS = settings.CANDIDATE_OBSERVATION_HOURS
CANDIDATE_MIN_SUCCESS = settings.CANDIDATE_MIN_SUCCESS
CANDIDATE_MIN_SUCCESS_RATE = settings.CANDIDATE_MIN_SUCCESS_RATE
CANDIDATE_MAX_LATENCY = settings.CANDIDATE_MAX_LATENCY
AUTO_PROMOTE_THRESHOLD = settings.AUTO_PROMOTE_THRESHOLD

HEALTH_HISTORY_DAYS = settings.HEALTH_HISTORY_DAYS
PREDICT_THRESHOLD = settings.PREDICT_THRESHOLD

ENABLE_FIXED_OPTIMIZATION = settings.ENABLE_FIXED_OPTIMIZATION
FIXED_OPTIMIZATION_THRESHOLD = settings.FIXED_OPTIMIZATION_THRESHOLD

IPTV_SOURCES = settings.IPTV_SOURCES
HEADERS = settings.HEADERS

RAW_SOURCES = settings.RAW_SOURCES
DIRECT_SOURCES = settings.DIRECT_SOURCES
ENABLE_GITHUB_PROXY = settings.ENABLE_GITHUB_PROXY
GITHUB_RAW_PROXIES = settings.GITHUB_RAW_PROXIES
GITHUB_PROXY_TIMEOUT = settings.GITHUB_PROXY_TIMEOUT
PROXY = ""

# 以下为原有常量，保持不变
M3U_FILE = "tv.m3u"
TXT_FILE = "tv.txt"
OUTPUT_CATEGORY_ORDER = ["央视", "卫视", "地方", "港澳台"]
CCTV_ORDER = [
    "CCTV-1", "CCTV-2", "CCTV-3", "CCTV-4", "CCTV-5", "CCTV-5+", "CCTV-6",
    "CCTV-7", "CCTV-8", "CCTV-9", "CCTV-10", "CCTV-11", "CCTV-12", "CCTV-13",
    "CCTV-14", "CCTV-15", "CCTV-16", "CCTV-17", "CCTV-4K", "CCTV-8K",
    "CCTV世界地理", "CCTV央视台球", "CCTV女性时尚", "CCTV怀旧剧场",
    "CCTV第一剧场", "CCTV风云足球", "CCTV老故事", "CGTN", "CGTN俄语",
    "CGTN法语", "CGTN纪录", "CGTN西语", "CGTN阿语"
]

ENABLE_RETRY = True
RETRY_MAX_ATTEMPTS = 3
RETRY_BACKOFF_FACTOR = 2
RETRY_MAX_WAIT = 60

DEMO_FILE = ROOT_DIR / "demo.txt"
ALIAS_FILE = ROOT_DIR / "alias.txt"
BLACKLIST_FILE = ROOT_DIR / "blacklist.txt"
DATABASE_PATH = DATA_DIR / "iptv_cache.db"

# 从 constants 导入省份等（避免重复定义）
from src.constants import PROVINCES, CCTV_ORDER as CCTVSORT, HK_MACAU_TAIWAN_KEYWORDS
PROVINCES = PROVINCES
HK_MACAU_TAIWAN_KEYWORDS = HK_MACAU_TAIWAN_KEYWORDS
CCTV_ORDER = CCTVSORT
